/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JFrame;

/**
 *
 * @author Rafael Lemos
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        pessoaFis = new javax.swing.JMenuItem();
        pessoaJur = new javax.swing.JMenuItem();
        usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PedidoEncomenda = new javax.swing.JMenuItem();
        PedidoPass = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisTur");

        javax.swing.GroupLayout jdpPane1Layout = new javax.swing.GroupLayout(jdpPane1);
        jdpPane1.setLayout(jdpPane1Layout);
        jdpPane1Layout.setHorizontalGroup(
            jdpPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jdpPane1Layout.setVerticalGroup(
            jdpPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/imagens/icons/Botoes_5041_users_two_48.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        pessoaFis.setText("Pessoa Física");
        pessoaFis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaFisActionPerformed(evt);
            }
        });
        jMenu1.add(pessoaFis);

        pessoaJur.setText("Pessoa Jurídica");
        pessoaJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaJurActionPerformed(evt);
            }
        });
        jMenu1.add(pessoaJur);

        usuario.setText("Usuário");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/imagens/icons/Botoes_5044_box_48.png"))); // NOI18N
        jMenu2.setText("Pedido");

        PedidoEncomenda.setText("Encomenda");
        PedidoEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoEncomendaActionPerformed(evt);
            }
        });
        jMenu2.add(PedidoEncomenda);

        PedidoPass.setText("Passagem");
        PedidoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoPassActionPerformed(evt);
            }
        });
        jMenu2.add(PedidoPass);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/imagens/icons/Elegantes_0029_Paper-pencil.png"))); // NOI18N
        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPane1)
        );

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Nessa tela é onde iremos cadastras os clientes pessoa física e jurídica.
     * @param evt 
     */
    private void pessoaFisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaFisActionPerformed
        // TODO add your handling code here:
        PessoaFisica objPessoaFis = new PessoaFisica();
        jdpPane1.add(objPessoaFis);
        objPessoaFis.setVisible(true);
    }//GEN-LAST:event_pessoaFisActionPerformed
    /**
     *  Chama a tela de cadastro de usuário.
     * @param evt 
     */
    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        CadastroUsuario cadUsuario = new CadastroUsuario();
        jdpPane1.add(cadUsuario);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioActionPerformed

    private void PedidoEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoEncomendaActionPerformed
        Encomendas objEnc = new Encomendas();
        jdpPane1.add(objEnc);
        objEnc.setVisible(true);
    }//GEN-LAST:event_PedidoEncomendaActionPerformed

    private void PedidoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoPassActionPerformed
        Passagens pass = new Passagens();
        jdpPane1.add(pass);
        pass.setVisible(true);
    }//GEN-LAST:event_PedidoPassActionPerformed

    private void pessoaJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaJurActionPerformed
        PessoaJuridica objPessoaJur = new PessoaJuridica();
        jdpPane1.add(objPessoaJur);
        objPessoaJur.setVisible(true);
    }//GEN-LAST:event_pessoaJurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PedidoEncomenda;
    private javax.swing.JMenuItem PedidoPass;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPane1;
    private javax.swing.JMenuItem pessoaFis;
    private javax.swing.JMenuItem pessoaJur;
    private javax.swing.JMenuItem usuario;
    // End of variables declaration//GEN-END:variables
}
